# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Changelog
#         uses: Bullrich/generate-release-changelog@master
#         id: Changelog
#         env:
#           REPO: ${{ github.repository }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 


      - uses: softprops/action-gh-release@v1
        with:
          files: aa
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          generate_release_notes: true
          append_body: true

